spring:
  datasource:
    generate-unique-name: false
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: true
    spring.h2.console.settings.web-allow-others: false
  jpa:
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect